#!/usr/bin/env bash

temp-mc=$(grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_label | head -n1 | cut -d':' -f1 | sed 's/label/input/' | xargs cat)

if[[-z $temp-mc]]; then
    echo "Error: Unable to read CPU temperature."
    exit 1
fi
temp-c=$(echo "scale=2; $temp-mc / 1000" | bc)
temp-f=$(echo "scale=2; ($temp-c * 9/5) + 32" | bc)
echo "Celcius: $temp-c C"
echo "Fahrenheit: $temp-f F"
# Following script outputs current cpu die temperature in milidegree-celcius, convert it to celcius and fahrenheit and display as:
#
# Celcius: 42.0 C
# Fahrenheit: 107.6 F
