#!/usr/bin/env bash
pass(){
    local length=$1
    if [[ -z "$length" || "$length" -lt 1 ]]; then
        echo "Syntax $0 [password_length]"
        return 1
    fi
    tr -dc 'A-Za-z0-9!@#$%^&*()-_+=' < /dev/urandom | head -c "$length"
    echo ""
}

if [[ $# -ne 1 ]]; then
    echo "Syntax $0 [password_length]"
    exit 1
fi
pass "$1"
